# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40bd9bd691e2ed5ba02c52288f417b5b0b5f48ef10bbca9d80477ccb308c5db82b2f9431cf0fdf41ea1858665e302b6be8375fa450c7e79502d2ea6e656f136

test:
  secret_key_base: c1765aaad1eb2047c1c86b6d65203f71135407b5b0cc768f56145af29f5d215eafb1cf13b08efb25fc2f2855851c10be1dbb67d271c3c9279437853edd316da7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
